# Generated by Django 5.1.6 on 2025-02-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('Rank', models.CharField(max_length=20)),
                ('ward', models.TextField()),
            ],
        ),
    ]
