# Generated by Django 5.1.6 on 2025-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='image',
            field=models.ImageField(blank=True, upload_to='nurse_images/'),
        ),
    ]
