# Generated by Django 4.2 on 2025-03-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0004_nurse_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='student_pictures/')),
                ('student_name', models.CharField(max_length=255)),
                ('student_bio', models.TextField()),
            ],
        ),
    ]
